export const SITE_CONFIG = {
  siteName: "ROOF EXPRESS",
  siteUrl: process.env.SITE_URL || "https://roof-ex.com",
  phone: "650-666-5554",
  phoneFormatted: "(650) 666-5554",
  supportPhone: "650-666-5541",
  southBayPhone: "650-666-5477",
  email: "sales@roof-ex.com",
  license: "CSLB #1072766",
  address: {
    street: "58 West Portal Ave",
    city: "San Francisco",
    state: "CA",
    zip: "94127",
    full: "58 West Portal Ave, San Francisco, CA 94127",
  },
  paloAltoOffice: {
    street: "3790 El Camino Real",
    city: "Palo Alto",
    state: "CA",
    zip: "94306",
    full: "3790 El Camino Real, Palo Alto, CA 94306",
  },
  hours: {
    weekdays: "8:00 AM – 5:00 PM",
    saturday: "8:00 AM – 5:00 PM",
    sunday: "By Appointment",
    emergency: "24/7",
    display: [
      { day: "Monday", hours: "8:00 AM – 5:00 PM" },
      { day: "Tuesday", hours: "8:00 AM – 5:00 PM" },
      { day: "Wednesday", hours: "8:00 AM – 5:00 PM" },
      { day: "Thursday", hours: "8:00 AM – 5:00 PM" },
      { day: "Friday", hours: "8:00 AM – 5:00 PM" },
      { day: "Saturday", hours: "8:00 AM – 5:00 PM" },
      { day: "Sunday", hours: "By Appointment" },
    ],
    schema: [
      { dayOfWeek: "Monday", opens: "08:00", closes: "17:00" },
      { dayOfWeek: "Tuesday", opens: "08:00", closes: "17:00" },
      { dayOfWeek: "Wednesday", opens: "08:00", closes: "17:00" },
      { dayOfWeek: "Thursday", opens: "08:00", closes: "17:00" },
      { dayOfWeek: "Friday", opens: "08:00", closes: "17:00" },
      { dayOfWeek: "Saturday", opens: "08:00", closes: "17:00" },
    ],
  },
  social: {
    facebook: "https://www.facebook.com/roof.exp/",
    instagram: "https://www.instagram.com/roof_exp/",
    youtube: "https://www.youtube.com/@Roof-Express",
    tiktok: "https://www.tiktok.com/@roof.express",
    yelp: "https://www.yelp.com/biz/roof-express-san-francisco",
  },
  manufacturerProfiles: {
    gaf: "https://www.gaf.ca/en-ca/roofing-contractors/residential/usa/ca/san-francisco/roof-express-1146713",
    certainteed: "https://www.certainteed.com/profiles/RoofExpress",
    owensCorning: "https://www.owenscorning.com/en-us/roofing/contractors/contractor-profile/243660",
    bbb: "https://www.bbb.org/us/ca/san-francisco/profile/roofing-contractors/roof-express-1116-926196",
    cslb: "https://cslb.ca.gov/OnlineServices/CheckLicenseII/LicenseDetail.aspx?LicNum=1072766",
  },
  geo: {
    latitude: 37.7397,
    longitude: -122.4714,
  },
  serviceArea: "San Francisco Bay Area",
  defaultDescription: "ROOF EXPRESS is a Diamond Certified, GAF Master Elite, CertainTeed Select ShingleMaster roofing contractor serving the Bay Area. Roof repair, replacement, flat roofing, gutters & skylights. CSLB #1072766.",
  defaultImage: "/opengraph.jpg",
  schemaImage: "/images/roof-express-team.webp",
};
